Repository codestates-seb/seb41_main_007, pull requests merged in 2023-01, with the labels that each got.

#34 [BE Refactor] Cart api 구조 변경
  server/farm/src/main/java/com/bzzzzz/farm/cart/controller/CartController.java
  server/farm/src/main/java/com/bzzzzz/farm/cart/controller/CartProductController.java
  server/farm/src/main/java/com/bzzzzz/farm/cart/service/CartProductService.java
  server/farm/src/main/java/com/bzzzzz/farm/cart/service/CartService.java
Labels: [BE], [Refactor]

#37 Be/product
  server/farm/src/main/java/com/bzzzzz/farm/exception/ExceptionCode.java
  server/farm/src/main/java/com/bzzzzz/farm/product/controller/MainController.java
  server/farm/src/main/java/com/bzzzzz/farm/product/controller/ProductController.java
  server/farm/src/main/java/com/bzzzzz/farm/product/controller/ProductSubController.java
  server/farm/src/main/java/com/bzzzzz/farm/product/dto/ProductOptionPatchDto.java
  server/farm/src/main/java/com/bzzzzz/farm/product/dto/ProductOptionPostDto.java
  server/farm/src/main/java/com/bzzzzz/farm/product/dto/ProductPatchDto.java
  server/farm/src/main/java/com/bzzzzz/farm/product/dto/ProductPostDto.java
  server/farm/src/main/java/com/bzzzzz/farm/product/entity/Product.java
  server/farm/src/main/java/com/bzzzzz/farm/product/mapper/ProductMapper.java
  server/farm/src/main/java/com/bzzzzz/farm/product/repository/ProductRepository.java
  server/farm/src/main/java/com/bzzzzz/farm/product/service/ProductCategoryService.java
  server/farm/src/main/java/com/bzzzzz/farm/product/service/ProductOptionService.java
  server/farm/src/main/java/com/bzzzzz/farm/product/service/ProductService.java
Labels: [BE], [Feat]

#42 [BE FEAT] 관리자 권한 및 접근 권한 추가
  server/farm/build.gradle
  server/farm/src/main/java/com/bzzzzz/farm/auth/filter/JwtAuthenticationFilter.java
  server/farm/src/main/java/com/bzzzzz/farm/auth/filter/JwtVerificationFilter.java
  server/farm/src/main/java/com/bzzzzz/farm/auth/handler/OAuth2MemberSuccessHandler.java
  server/farm/src/main/java/com/bzzzzz/farm/auth/jwt/JwtTokenizer.java
  server/farm/src/main/java/com/bzzzzz/farm/config/SecurityConfiguration.java
  server/farm/src/main/java/com/bzzzzz/farm/config/WebMvcConfig.java
  server/farm/src/main/java/com/bzzzzz/farm/exception/ExceptionCode.java
  server/farm/src/main/java/com/bzzzzz/farm/member/controller/MemberController.java
  server/farm/src/main/java/com/bzzzzz/farm/member/dto/LoginDto.java
  server/farm/src/main/java/com/bzzzzz/farm/member/dto/MemberDto.java
  server/farm/src/main/java/com/bzzzzz/farm/member/entity/Member.java
  server/farm/src/main/java/com/bzzzzz/farm/member/service/MemberService.java
  server/farm/src/main/java/com/bzzzzz/farm/security/attribute/OAuthAttributes.java
  server/farm/src/main/java/com/bzzzzz/farm/security/config/JwtSecurityConfig.java
  server/farm/src/main/java/com/bzzzzz/farm/security/config/SecurityConfig.java
  server/farm/src/main/java/com/bzzzzz/farm/security/config/WebMvcConfig.java
  server/farm/src/main/java/com/bzzzzz/farm/security/controller/AuthController.java
  server/farm/src/main/java/com/bzzzzz/farm/security/dto/LoginDto.java
  server/farm/src/main/java/com/bzzzzz/farm/security/dto/TokenDto.java
  server/farm/src/main/java/com/bzzzzz/farm/security/dto/TokenRequestDto.java
  server/farm/src/main/java/com/bzzzzz/farm/security/filter/JwtVerificationFilter.java
  server/farm/src/main/java/com/bzzzzz/farm/security/handler/MemberAccessDeniedHandler.java
  server/farm/src/main/java/com/bzzzzz/farm/security/handler/MemberAuthenticationEntryPoint.java
  server/farm/src/main/java/com/bzzzzz/farm/security/handler/MemberAuthenticationFailureHandler.java
  server/farm/src/main/java/com/bzzzzz/farm/security/handler/MemberAuthenticationSuccessHandler.java
  server/farm/src/main/java/com/bzzzzz/farm/security/jwt/JwtTokenizer.java
  server/farm/src/main/java/com/bzzzzz/farm/security/refresh/RefreshToken.java
  server/farm/src/main/java/com/bzzzzz/farm/security/refresh/RefreshTokenRepository.java
  server/farm/src/main/java/com/bzzzzz/farm/security/service/AuthService.java
  server/farm/src/main/java/com/bzzzzz/farm/security/service/CustomOAuth2MemberService.java
  server/farm/src/main/java/com/bzzzzz/farm/security/utils/CustomAuthorityUtils.java
  server/farm/src/main/java/com/bzzzzz/farm/security/utils/ErrorResponder.java
  server/farm/src/main/java/com/bzzzzz/farm/security/utils/MemberDetailsService.java
  server/farm/src/main/resources/application-dev.yml
  server/farm/src/main/resources/application-secret.yml
Labels: [BE], [Feat]

#61 Product 관련 Controller 테스트 케이스 및 api 문서화 완료
  server/farm/src/docs/asciidoc/index.adoc
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/product/ProductOptionPatchDto.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/MainControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/ProductSubControllerTest.java
Labels: [BE], [Test]

#66 CategoryController, LikeController, CartController 테스트 및 API 문서화 완료
  server/farm/src/docs/asciidoc/index.adoc
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/cart/CartProductPatchDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/cart/CartProductPostDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/category/CategoryPatchDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/category/CategoryPostDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/like/LikeRequestDto.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/CartControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/CategoryControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/LikeControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/ProductControllerTest.java
Labels: [BE], [Test]

#68 쿼리DSL 적용 완료
  server/farm/build.gradle
  server/farm/src/main/java/com/bzzzzz/farm/config/QuerydslConfig.java
  server/farm/src/main/java/com/bzzzzz/farm/controller/MainController.java
  server/farm/src/main/java/com/bzzzzz/farm/controller/ProductController.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/ProductRepository.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/querydsl/ProductRepositoryCustom.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/querydsl/ProductRepositoryImpl.java
  server/farm/src/main/java/com/bzzzzz/farm/service/ProductService.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/MainControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/ProductControllerTest.java
Labels: [BE], [Refactor]

#73 Be/product
  server/farm/src/main/java/com/bzzzzz/farm/controller/MainController.java
  server/farm/src/main/java/com/bzzzzz/farm/controller/ProductController.java
  server/farm/src/main/java/com/bzzzzz/farm/mapper/ProductMapper.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/product/ProductSimpleResponseDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/entity/Product.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/ProductRepository.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/querydsl/ProductRepositoryCustom.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/querydsl/ProductRepositoryCustomImpl.java
  server/farm/src/main/java/com/bzzzzz/farm/service/LikeService.java
  server/farm/src/main/java/com/bzzzzz/farm/service/ProductCategoryService.java
  server/farm/src/main/java/com/bzzzzz/farm/service/ProductOptionService.java
  server/farm/src/main/java/com/bzzzzz/farm/service/ProductService.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/MainControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/ProductControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/controller/ProductSubControllerTest.java
  server/farm/src/test/java/com/bzzzzz/farm/service/ProductCategoryServiceTest.java
  server/farm/src/test/java/com/bzzzzz/farm/service/ProductOptionServiceTest.java
  server/farm/src/test/java/com/bzzzzz/farm/service/ProductServiceTest.java
Labels: [BE], [Test]

#78 Be/order
  server/farm/build.gradle
  server/farm/src/main/java/com/bzzzzz/farm/config/ParcelTrackingConfig.java
  server/farm/src/main/java/com/bzzzzz/farm/controller/OrderController.java
  server/farm/src/main/java/com/bzzzzz/farm/mapper/OrderMapper.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/ParcelTrackingResponseDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/order/OrderPostDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/order/OrderProductPostDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/entity/Order.java
  server/farm/src/main/java/com/bzzzzz/farm/model/entity/OrderProduct.java
  server/farm/src/main/java/com/bzzzzz/farm/repository/OrderRepository.java
  server/farm/src/main/java/com/bzzzzz/farm/service/OrderService.java
  server/farm/src/main/java/com/bzzzzz/farm/service/ProductOptionService.java
Labels: [BE], [Feat]

#81 주문 생성, 조회, 취소, 변경 구현
  server/farm/src/main/java/com/bzzzzz/farm/controller/OrderController.java
  server/farm/src/main/java/com/bzzzzz/farm/mapper/OrderMapper.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/order/OrderProductResponseDto.java
  server/farm/src/main/java/com/bzzzzz/farm/model/dto/order/OrderResponseDto.java
  server/farm/src/main/java/com/bzzzzz/farm/service/OrderService.java
Labels: [BE], [Feat]
